FROM node:14 as build

RUN npm i -g gatsby-cli

WORKDIR /app
COPY ["package.json", "package-lock.json", "./"]
RUN npm install

COPY [".", "./"]

EXPOSE 8000

CMD ["gatsby", "develop", "-H", "0.0.0.0"]