module.exports = {
<<<<<<< HEAD
  "@home": "src/components/home",
  "@navbar": "src/components/navbar",
  "@people": "src/components/people",
  "@portfolio": "src/components/portfolio",
  "@wiki": "src/components/wiki",
  "@components": "src/components",
  "@globals": "src/globals",
  "@hooks": "src/hooks",
  "@images": "src/images",
  "@pages": "src/pages",
  "@constants": "src/globals/constants",
  "@testConstants": "src/globals/testConstants",
  "@useAPI": "src/hooks/useAPI",
  "@api": "src/globals/api",
  "@contexts": "src/globals/contexts",
  "@styles": "src/globals/styles",
=======
  "@home": "src/components/home/",
  "@navbar": "src/components/navbar/",
  "@people": "src/components/people/",
  "@portfolio": "src/components/portfolio/",
  "@components": "src/components/",
  "@globals": "src/globals/",
  "@hooks": "src/hooks/",
  "@images": "src/images/",
  "@pages": "src/pages/",
>>>>>>> 5fcc204cad8d3d01c1b14e12300774fd9879b3e9
}